scheme: Gemini
darkmode: true

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-categories
  
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
